#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#home: 
#    path: /home
#    defaults: { _controller: 'App\Controller\HomeController::home' }

#admin: 
#     path: /admin/admin
#     defaults: { _controller: 'App\Controller\HomeController::admin' }